language: php

php:
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.5

env:
  - MONGO_VERSION=1.2.12

services: mongodb

before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer update --prefer-source --dev --no-interaction

script:
  - cd ./tests
  - phpunit
