<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SdsDoctrineExtensionsModule\Module' => __DIR__ . '/Module.php',
    'SdsDoctrineExtensions\AuthUser'  => __DIR__ . '/vendor/SdsDoctrineExtensions/lib/SdsDoctrineExtensions/AuthUser.php',
);