<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SdsDoctrineExtensionsModule\Module'            => __DIR__ . '/Module.php',
    'SdsDoctrineExtensionsModule\Factory\Find'      => __DIR__ . '/src/SdsDoctrineExtensionsModule/Factory/Find.php',
    'SdsDoctrineExtensionsModule\Factory\FindAll'   => __DIR__ . '/src/SdsDoctrineExtensionsModule/Factory/FindAll.php',
    'SdsDoctrineExtensionsModule\Factory\FindBy'    => __DIR__ . '/src/SdsDoctrineExtensionsModule/Factory/FindBy.php',
    'SdsDoctrineExtensionsModule\Factory\FindOneBy' => __DIR__ . '/src/SdsDoctrineExtensionsModule/Factory/FindOneBy.php',
    'SdsDoctrineExtensions\Utils' => __DIR__ . '/vendor/SdsDoctrineExtensions/lib/SdsDoctrineExtensions/Utils.php',      
    'SdsDoctrineExtensions\Listener\ActiveUser' => __DIR__ . '/vendor/SdsDoctrineExtensions/lib/SdsDoctrineExtensions/Listener/ActiveUser.php',       
    'SdsDoctrineExtensions\Behaviour\User' => __DIR__ . '/vendor/SdsDoctrineExtensions/lib/SdsDoctrineExtensions/Behaviour/User.php',        
    'SdsDoctrineExtensions\Behaviour\AuthUser' => __DIR__ . '/vendor/SdsDoctrineExtensions/lib/SdsDoctrineExtensions/Behaviour/AuthUser.php',  
    'SdsDoctrineExtensions\Behaviour\ActiveUser' => __DIR__ . '/vendor/SdsDoctrineExtensions/lib/SdsDoctrineExtensions/Behaviour/ActiveUser.php',  
    'SdsDoctrineExtensions\Behaviour\Stamped' => __DIR__ . '/vendor/SdsDoctrineExtensions/lib/SdsDoctrineExtensions/Behaviour/Stamped.php',      
    'SdsDoctrineExtensions\Behaviour\Audited' => __DIR__ . '/vendor/SdsDoctrineExtensions/lib/SdsDoctrineExtensions/Behaviour/Audited.php',     
    'SdsDoctrineExtensions\Behaviour\Stamped\UpdatedOn' => __DIR__ . '/vendor/SdsDoctrineExtensions/lib/SdsDoctrineExtensions/Behaviour/Stamped/UpdatedOn.php', 
    'SdsDoctrineExtensions\Behaviour\Stamped\UpdatedBy' => __DIR__ . '/vendor/SdsDoctrineExtensions/lib/SdsDoctrineExtensions/Behaviour/Stamped/UpdatedBy.php',     
    'SdsDoctrineExtensions\Behaviour\Stamped\CreatedOn' => __DIR__ . '/vendor/SdsDoctrineExtensions/lib/SdsDoctrineExtensions/Behaviour/Stamped/CreatedOn.php',      
    'SdsDoctrineExtensions\Behaviour\Stamped\CreatedBy' => __DIR__ . '/vendor/SdsDoctrineExtensions/lib/SdsDoctrineExtensions/Behaviour/Stamped/CreatedBy.php',             
);