<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SdsDoctrineExtensionsModule\Module'            => __DIR__ . '/Module.php',
    'SdsDoctrineExtensionsModule\Factory\Find'      => __DIR__ . '/src/SdsDoctrineExtensionsModule/Factory/Find.php',
    'SdsDoctrineExtensionsModule\Factory\FindAll'   => __DIR__ . '/src/SdsDoctrineExtensionsModule/Factory/FindAll.php',
    'SdsDoctrineExtensionsModule\Factory\FindBy'    => __DIR__ . '/src/SdsDoctrineExtensionsModule/Factory/FindBy.php',
    'SdsDoctrineExtensionsModule\Factory\FindOneBy' => __DIR__ . '/src/SdsDoctrineExtensionsModule/Factory/FindOneBy.php',
    'SdsDoctrineExtensions\Utils' => __DIR__ . '/vendor/SdsDoctrineExtensions/lib/SdsDoctrineExtensions/Utils.php',      
    'SdsDoctrineExtensions\User' => __DIR__ . '/vendor/SdsDoctrineExtensions/lib/SdsDoctrineExtensions/User.php',        
    'SdsDoctrineExtensions\AuthUser' => __DIR__ . '/vendor/SdsDoctrineExtensions/lib/SdsDoctrineExtensions/AuthUser.php',  
    'SdsDoctrineExtensions\ActiveUser' => __DIR__ . '/vendor/SdsDoctrineExtensions/lib/SdsDoctrineExtensions/ActiveUser.php',  
    'SdsDoctrineExtensions\Stamped' => __DIR__ . '/vendor/SdsDoctrineExtensions/lib/SdsDoctrineExtensions/Stamped.php',      
    'SdsDoctrineExtensions\Audit' => __DIR__ . '/vendor/SdsDoctrineExtensions/lib/SdsDoctrineExtensions/Audit.php',     
    'SdsDoctrineExtensions\Stamped\UpdatedOn' => __DIR__ . '/vendor/SdsDoctrineExtensions/lib/SdsDoctrineExtensions/Stamped/UpdatedOn.php', 
    'SdsDoctrineExtensions\Stamped\UpdatedBy' => __DIR__ . '/vendor/SdsDoctrineExtensions/lib/SdsDoctrineExtensions/Stamped/UpdatedBy.php',     
    'SdsDoctrineExtensions\Stamped\CreatedOn' => __DIR__ . '/vendor/SdsDoctrineExtensions/lib/SdsDoctrineExtensions/Stamped/CreatedOn.php',      
    'SdsDoctrineExtensions\Stamped\CreatedBy' => __DIR__ . '/vendor/SdsDoctrineExtensions/lib/SdsDoctrineExtensions/Stamped/CreatedBy.php',             
);